apiVersion: v1
kind: Service
metadata:
  name: django2-svc
  labels:
    app: django2
spec:
  type: ClusterIP
  selector:
    app: django2
  ports:
    - port: 8000
      targetPort: 8000
      name: http